name: Build LaTeX Judiciary Manual
on: workflow_dispatch
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ASWWU_Judiciary_Manual.tex
          latexmk_use_xelatex: true
      - name: Display structure of downloaded files
        run: |
          git config --global user.email "ASWWU.Parliamentarian@wallawalla.edu"
          git config --global user.name "ASWWU-Parliamentarian"
          git add ASWWU_Judiciary_Manual.pdf
          git commit -m "Last built at $(date)"
          git push